import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Custom function to sort meeting files by date (newest first)
 */
function generateSortedMeetings() {
  // Import fs to read directory contents
  const fs = require('fs');
  const path = require('path');
  
  try {
    const meetingsDir = path.join(__dirname, 'docs', 'meetings');
    const files = fs.readdirSync(meetingsDir)
      .filter(file => file.endsWith('.md') && file.startsWith('meeting-'))
      .map(file => {
        // Extract date from filename (meeting-YYYY-MM-DD.md)
        const match = file.match(/meeting-(\d{4}-\d{2}-\d{2})/);
        if (match) {
          return {
            file: file.replace('.md', ''),
            date: new Date(match[1]),
            sortKey: match[1] // YYYY-MM-DD for sorting
          };
        }
        return null;
      })
      .filter(item => item !== null)
      .sort((a, b) => b.sortKey.localeCompare(a.sortKey)) // Sort newest first
      .map(item => `meetings/${item.file}`);
    
    return files;
  } catch (error) {
    console.error('Error generating sorted meetings:', error);
    return [
    ];
  }
}

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // Main documentation index
    'index',
    
    // Meetings category with all meeting files
    {
      type: 'category',
      label: 'Meetings',
      items: [
        {
          type: 'doc',
          id: 'meetings',
          label: 'Meetings Overview',
          className: 'hidden-from-nav', // This will be hidden via CSS
        },
        // Use custom sorted meetings instead of autogenerated
        ...generateSortedMeetings(),
      ],
    },
    
    // Events category
    {
      type: 'category',
      label: 'Events',
      items: [
        {
          type: 'autogenerated',
          dirName: 'events',
        },
      ],
    },
    
    // Templates category
    {
      type: 'category',
      label: 'Templates',
      items: [
        {
          type: 'autogenerated',
          dirName: 'templates',
        },
      ],
    },
    
    // Tutorial category (preserves existing structure)
    {
      type: 'category',
      label: 'Tutorial',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial',
        },
      ],
    },
    
    // Archive category
    {
      type: 'category',
      label: 'Archive',
      items: [
        {
          type: 'autogenerated',
          dirName: 'archive',
        },
      ],
    },
    
    // Other standalone docs
    'schedule',
    'contact',
    'content-management-guide',
  ],
};

export default sidebars;
