backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "docs"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Sidebar Position", name: "sidebar_position", widget: "number", default: 1, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: false, required: false}

  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "meeting-notes"
    label: "Meeting Notes"
    folder: "docs/meeting-notes"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "docs"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Meeting Type", name: "meeting_type", widget: "select", options: ["General", "Technical", "Planning", "Review"], required: false}
      - {label: "Attendees", name: "attendees", widget: "list", required: false}
      - {label: "Agenda", name: "agenda", widget: "markdown", required: false}
      - {label: "Notes", name: "body", widget: "markdown"}
      - {label: "Action Items", name: "action_items", widget: "list", fields: [{label: "Item", name: "item", widget: "string"}, {label: "Assignee", name: "assignee", widget: "string"}, {label: "Due Date", name: "due_date", widget: "datetime"}], required: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: false, required: false}

  - name: "meeting-agendas"
    label: "Meeting Agendas"
    folder: "docs/meeting-agendas"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "docs"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Meeting Type", name: "meeting_type", widget: "select", options: ["General", "Technical", "Planning", "Review"], required: false}
      - {label: "Duration", name: "duration", widget: "string", required: false}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "Attendees", name: "attendees", widget: "list", required: false}
      - {label: "Topics", name: "topics", widget: "list", fields: [{label: "Topic", name: "topic", widget: "string"}, {label: "Presenter", name: "presenter", widget: "string"}, {label: "Duration", name: "duration", widget: "string"}], required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false, required: false}

  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "meetings"
    label: "Meetings"
    file: "docs/meetings.md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "schedule"
    label: "Schedule"
    file: "docs/schedule.md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "intro"
    label: "Introduction"
    file: "docs/intro.md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
